name: deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: create file
        run: ssh -o StrictHostKeyChecking=no azureuser@20.84.42.99 touch hola.txt

      - name: create file
        run: bash deploy.sh
